name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (pnpm)
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Python (uv)
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install frontend dev deps
        working-directory: frontend
        run: pnpm install

      - name: Pre-commit (same command as local)
        run: uvx pre-commit run -a

      - name: Frontend build
        working-directory: frontend
        run: pnpm build
      
      - name: Backend tests
        working-directory: backend
        run: uv run pytest -q
