name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Node / Frontend ----
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Frontend install
        run: pnpm -C frontend install --frozen-lockfile

      - name: Frontend build
        run: pnpm -C frontend build

      # ---- Python / Backend ----
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pipx install uv

      - name: Backend deps sync
        run: uv sync --project backend --frozen

      - name: Run pre-commit (lint/format)
        run: uvx pre-commit run -a

      - name: Run backend tests (unit + e2e)
        env:
          # e2eでOpen-Meteoモックが効くのでネット不要
          MODEL_BACKEND: persistence
        run: uv run --project backend pytest -q
