name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    name: Frontend Lint & TypeCheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 追加: pnpm をインストール
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      # 任意（Corepack を併用したい場合）
      - name: Enable Corepack
        run: corepack enable

      - name: Install deps (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: TypeCheck
        run: pnpm run typecheck

  backend:
    name: Backend Lint & TypeCheck & PyTest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements.txt
            backend/requirements-dev.txt

      - name: Install deps
        shell: bash
        run: |
          set -eux
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ ! -f requirements.txt ] && [ ! -f requirements-dev.txt ] && [ -f pyproject.toml ]; then
            pip install -e . || true
          fi

      - name: Lint (ruff/black/isort)
        run: |
          ruff check .
          black --check .
          isort --check-only .

      - name: TypeCheck (mypy)
        run: mypy --config-file backend/mypy.ini backend/app

      - name: PyTest
        run: pytest -q

  all-green:
    name: All Checks
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - run: echo "All green ✅"
