name: gemini

on:
  workflow_dispatch: {}
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: read

concurrency:
  group: gemini-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: false

jobs:
  draft-pr:
    # ai-task ラベル or @gemini-cli メンション で実行。手動トリガーも可。
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'ai-task') ||
      (github.event_name == 'issue_comment' && github.event.action == 'created' && contains(github.event.comment.body, '@gemini-cli'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install gemini-cli
        run: npm i -g @google/gemini-cli@latest

      - name: Prepare scoped settings (runner only)
        # リポジトリに含めない一時 .gemini/settings.json（後でコミット対象外）
        run: |
          mkdir -p .gemini
          cat > .gemini/settings.json <<'JSON'
          {
            "tools": {
              "allowed": ["read_file","write_file","replace","glob","search_file_content","web_fetch"],
              "blocked": ["run_shell_command"]
            },
            "workspace": { "includeDirectories": ["backend","frontend","tests"] }
          }
          JSON

      - name: Collect task from Issue/Comment
        id: prep
        uses: actions/github-script@v7
        with:
          script: |
            const ev = context.payload;
            let source = 'manual';
            let task = '';
            let num = context.runId;
            let base = ev.repository?.default_branch || 'main';

            if (context.eventName === 'issues' && ev.action === 'labeled' && ev.label?.name === 'ai-task') {
              source = `issue #${ev.issue.number}`;
              num = ev.issue.number;
              task = `Title: ${ev.issue.title}\n\nBody:\n${ev.issue.body || ''}`;
            } else if (context.eventName === 'issue_comment' && ev.action === 'created' && ev.comment?.body?.includes('@gemini-cli')) {
              source = (ev.issue?.pull_request ? `pr #${ev.issue.number}` : `issue #${ev.issue.number}`);
              num = ev.issue.number || context.runId;
              // メンションを除去して依頼本文を抽出
              task = (ev.comment.body || '').replace('@gemini-cli', '').trim();
            } else {
              task = 'No task provided (workflow_dispatch). Describe your task in the Issue and apply label "ai-task" or comment with @gemini-cli next time.';
            }

            core.setOutput('source', source);
            core.setOutput('task', task);
            core.setOutput('branch', `ai/gemini/${num}`);
            core.setOutput('base', base);

      - name: Run gemini (edit only backend/frontend/tests)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "### AI Task from ${{ steps.prep.outputs.source }}" > AI_SUMMARY.md
          printf '\n%s\n' "${{ steps.prep.outputs.task }}" >> AI_SUMMARY.md

          gemini --include-directories backend,frontend,tests \
            --approval-mode=auto_edit \
            --allowed-tools write_file,replace,read_file,glob \
            -m gemini-1.5-flash \
            "You are a repository code editor. Only modify files under backend/, frontend/, or tests/. Do not touch any other paths.
             Implement the task described in AI_SUMMARY.md with minimal, safe edits and clear commit-worthy changes.
             After applying edits, append a '### Changes' section with a concise bullet list to AI_SUMMARY.md."

      - name: Commit changes (limit paths; do not include .gemini)
        id: changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 変更の有無を backend/frontend/tests/AI_SUMMARY.md に限定して判定
          if git diff --quiet -- backend frontend tests AI_SUMMARY.md 2>/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes produced by gemini."
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            git add backend frontend tests AI_SUMMARY.md
            git commit -m "chore(ai): apply gemini task from ${{ steps.prep.outputs.source }}"
          fi

      - name: Create draft PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(ai): draft from ${{ steps.prep.outputs.source }}"
          body: |
            Generated by gemini-cli on CI.

            - Source: ${{ steps.prep.outputs.source }}
            - Scope: backend/, frontend/, tests/
            - Summary: See AI_SUMMARY.md
          commit-message: "chore(ai): apply gemini task from ${{ steps.prep.outputs.source }}"
          branch: ${{ steps.prep.outputs.branch }}
          base: ${{ steps.prep.outputs.base }}
          draft: true
          labels: ai-generated
          token: ${{ secrets.GITHUB_TOKEN }}
