name: Gitleaks (Secrets Scan)

on:
  pull_request:
    paths: ['**']
  push:
    branches: ['main', 'feature/**']
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for better detection)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # 無ければ削除OK（OSSは不要）
        with:
          args: detect --redact --verbose
