# .github/workflows/gitleaks.yml
name: gitleaks
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # org リポジトリの場合のみ必要（個人アカウントは不要）
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_ENABLE_COMMENTS: "true"
          GITLEAKS_ENABLE_SUMMARY: "true"
          # 必要ならバージョン固定も可: GITLEAKS_VERSION: "8.24.3"
