name: Lighthouse (Accessibility)

on:
  pull_request:
    paths: ['frontend/**']
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            frontend/pnpm-lock.yaml
            pnpm-lock.yaml

      - name: Install deps
        run: pnpm install

      - name: Build Next
        run: pnpm build

      - name: Run Lighthouse CI (accessibility only)
        run: pnpm dlx @lhci/cli autorun --config=./lighthouserc.json
